<?php

namespace LDS\PlatformBundle\Repository;

/**
 * CommentaireEtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireEtablissementRepository extends \Doctrine\ORM\EntityRepository
{
	  public function count_commentaire($login) {
    $query=$this->createQueryBuilder('a')
    ->select('COUNT(a.id)')
    ->where('a.login = :login')
    ->setParameters(['login'=> $login])->getQuery()->getSingleScalarResult();

    if ($query == 0) {
      return true;
    }
    else {
      return false;
    }
  }

     public function derniers_commentaires($e) {
    $query=$this->createQueryBuilder('a')
    ->select('a')
    ->where('a.etablissement = :e')
    ->orderBy('a.date', 'desc')
    ->setMaxResults(6)
    ->setParameters(['e'=> $e])
    ->getQuery()->getResult();
    return $query;
  }



}
