<?php

namespace LDS\PlatformBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
	 public function trouverEvenementInvalide ($page = 1, $max)
{
    $qb = $this->createQueryBuilder('a')
            ->where('a.valide = false')
            ->orderBy('a.nom', 'ASC');
    $query = $qb->getQuery();
$query->setFirstResult(($page-1) * $max)
->setMaxResults($max);
return new Paginator($query);
}
}
