<?php

namespace LDS\PlatformBundle\Repository;

/**
 * FavoriRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriEtablissementRepository extends \Doctrine\ORM\EntityRepository
{
}
