<?php

namespace LDS\PlatformBundle\Repository;

/**
 * FavoriEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriEvenementRepository extends \Doctrine\ORM\EntityRepository
{
}
