<?php

namespace LDS\PlatformBundle\Repository;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FicheSoireeRepository extends \Doctrine\ORM\EntityRepository
{
}
