<?php

namespace LDS\PlatformBundle\Repository;

/**
 * HorraireJourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HorraireJourRepository extends \Doctrine\ORM\EntityRepository
{
}
