<?php

namespace LDS\PlatformBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * MessageAdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageAdminRepository extends \Doctrine\ORM\EntityRepository
{

	public function countMessage() {
    $query=$this->createQueryBuilder('a')
    ->select('COUNT(a.id)')
    ->getQuery()->getSingleScalarResult();
    if ($query == 0) {
      return true;
    }
    else {
      return false;
    }
  }

    public function trouverMessageAdmin ($page = 1, $max)
{
    $qb = $this->createQueryBuilder('a')
            ->orderBy('a.date', 'ASC');
    $query = $qb->getQuery();
$query->setFirstResult(($page-1) * $max)
->setMaxResults($max);
return new Paginator($query);
}
}
