<?php

namespace LDS\PlatformBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ParticulierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticulierRepository extends \Doctrine\ORM\EntityRepository {

	// fonction pour la connexion
	public function count_particulier($login ,$password) {
		$query=$this->createQueryBuilder('a')
		->select('COUNT(a.login)')
		->where('a.login = :login')
		->andWhere('a.password = :password') 
		->setParameters(['login'=> $login,'password'=> $password])->getQuery()->getSingleScalarResult();

		if ($query == 1) {
			return true;
		}
		else {
			return false;
		}

	}

	public function count_login($login) {
		$query=$this->createQueryBuilder('a')
		->select('COUNT(a.login)')
		->where('a.login = :login')
		->setParameters(['login'=> $login])->getQuery()->getSingleScalarResult();

		if ($query == 1) {
			return true;
		}
		else {
			return false;
		}
	}
	


	public function count_mail($email) {

		$query=$this->createQueryBuilder('a')
		->select('COUNT(a.email)')
		->where('a.email = :email')
		->setParameters(['email'=> $email])->getQuery()->getSingleScalarResult();

		if ($query == 1) {
			return true;
		}
		else {
			return false;
		}
	}

	public function trouverParticulier($page = 1, $max)
	{
		$qb = $this->createQueryBuilder('a')
		->where('a.valide = true')
		->orderBy('a.login', 'ASC');
		$query = $qb->getQuery();
		$query->setFirstResult(($page-1) * $max)
		->setMaxResults($max);
		return new Paginator($query);
	}

}
