<?php

namespace LDS\PlatformBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{

	public function count_tag() {
    $query=$this->createQueryBuilder('a')
    ->select('COUNT(a.id)')
    ->where('a.valide = false')
    ->getQuery()->getSingleScalarResult();

    if ($query == 0) {
      return true;
    }
    else {
      return false;
    }
  }

  public function trouverTagInvalide ($page = 1, $max)
{
    $qb = $this->createQueryBuilder('a')
            ->where('a.valide = false')
            ->orderBy('a.nom', 'ASC');
    $query = $qb->getQuery();
$query->setFirstResult(($page-1) * $max)
->setMaxResults($max);
return new Paginator($query);
}

  public function trouverTagValide ()
{
    $query = $this->createQueryBuilder('a')
            ->where('a.valide = true')
            ->orderBy('a.nom', 'asc')
            ->getQuery()->getResult();
    return $query;
}

}
