<?php

namespace LDS\PlatformBundle\Repository;

/**
 * ProfessionnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VillesFranceFreeRepository extends \Doctrine\ORM\EntityRepository
{

	   public function autocompletion($data) {
    $query=$this->createQueryBuilder('a')
    ->select('a')
    ->where('a.villeNomReel like :data')
    ->orderBy('a.villeNomReel', 'asc')
    ->setMaxResults(6)
    ->setParameters(['data'=> $data . '%'])
    ->getQuery()->getResult();
    return $query;
  }
}